ALTER TABLE users
ADD COLUMN IF NOT EXISTS mobile VARCHAR(15) NULL,
ADD COLUMN IF NOT EXISTS branch_location VARCHAR(100) NULL,
ADD COLUMN IF NOT EXISTS profile_photo VARCHAR(255) NULL DEFAULT 'default.png',
ADD COLUMN IF NOT EXISTS last_login DATETIME NULL,
ADD COLUMN IF NOT EXISTS account_status ENUM('Active','Inactive') DEFAULT 'Active';
